### ISSUE TITLE
Skinned mesh bounding box gets screwed up sometimes.

### ISSUE THREAD

**Issue by Nettehlol** [rurre/PumkinsAvatarTools#4] opened 2018-11-21 14:15 UTC
http://prntscr.com/ll5z3s

I assume it's from copying skinned mesh from other ava., 0.5b was used.

BB looks kinda the same on all borked ones - at the bottom of feet.

**Comment by rurre** [comment] 2018-11-22 08:51
This was caused by the root bone being incorrectly assigned (it generally shouldn't have even been changed). Should be fixed.

**Closed by rurre** 2018-11-22 08:51 UTC
