### ISSUE TITLE
Colliders under empty game objects do not get transferred. 

### ISSUE THREAD

**Issue by Nettehlol** [rurre/PumkinsAvatarTools#1] opened 2018-11-14 15:11 UTC
Not sure if it's possible, but would be great if tool could support colliders (sphere/capsule) that are under empty game objects, as those are easier to move to desired place.

**Comment by rurre** [comment] 2018-11-14 16:39
At the moment empty game objects aren't being copied over by design because it's kind of tricky to distinguish armature bones from empty game objects added after.

But I think I could support it by copying game objects and their parents if a child at the end of the hierarchy has components on it.

I will look into it.

**Comment by rurre** [comment] 2019-09-22 09:27
GameObjects now get transferred. Just grab the latest release!

**Closed by rurre** 2019-09-22 09:27 UTC
Labels: enhancement
